e_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_pk>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('remove/<int:product_pk>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_pk>/', views.full_remove, name='full_remove'),
]

e_shop/e_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_shopee.urls')),
    path('search', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

e_shop/e_shopee/urls.py
from . import views
from django.urls import path


app_name = 'e_shopee'

urlpatterns = [
    path('', views.all_product_category, name='all_product_category'),
    path('<slug:c_slug>/', views.all_product_category, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.all_product_details, name='product_category_details'),
]

e_shop/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('', views.search_result, name='search_result'),
]

e_shop/cart/models.py
from django.db import models
from e_shopee.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.Product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

e_shop/e_shopee/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('e_shopee:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('e_shopee:product_category_details ', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

e_shop/search_app/models.py
from django.db import models

# Create your models here.

e_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from e_shopee.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_pk):
    products = Product.objects.get(id=product_pk)
    try:
        cart = Cart.objects.get(cart_id=request.user.id)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=products, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=request.user.id)
        cart_items = CartItem.objects.filter(cart=cart, active=True)[0]
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_pk):
    cart = Cart.objects.get(cart_id=request.user.id)
    product = get_object_or_404(Product, id=product_pk)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')


def full_remove(request, product_pk):
    cart = Cart.objects.get(cart_id=request.user.id)
    product = get_object_or_404(Product, id=product_pk)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

e_shop/e_shopee/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def all_product_category(request, c_slug=None):
    c_page = None
    products = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
        paginator = Paginator(products_list, 3)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)
        return render(request, 'category.html', {'category': c_page, 'products': products})


def all_product_details(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

e_shop/search_app/views.py
from django.shortcuts import render
from e_shopee.models import Product
from django.db.models import Q


def search_result(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

e_shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div>
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>
<div class="container"></div>

e_shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        THIS IS THE CART PAGE. PROCEED TO REVIEW YOUR ITEMS AND PLACE THE ORDER
{% endblock %}
{% block title %}
    CART - E STORE COMPANY PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> YOUR SHOPPING CART EMPTY</h1><br>
        <p>PLEASE CLICK <a href="{% url e_shopee:all_product_category %}"> HERE</a>TO CONTINUE SHOPPING</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">YOUR SHOPPING CART</h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        YOUR ITEMS
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" alt="" class="float-left rounded custom_image" width="100%" height="100px"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        PRICE: $ {{cart_item.product.price}}
                        <br>
                        QTY : {{cart_item.quantity}} x $ {{cart.item}}
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    <td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                    </td>
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i> </a>
                        &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %} " class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                        {% else %}
                         <td>
                        &nbsp;&nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                </tr>
                        {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        CHECKOUT
                    </th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    PLEASE REVIEW YOUR SHOPPING CART ITEMS BEFORE PROCEEDING WITH THE ORDER PAYMENT.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    YOUR TOTAL IS : <strong> {{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'e_shopee:all_product_category' %}" class="btn btn-primary btn-block my_custom_button">CONTINUE SHOPPING</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

e_shop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        WELCOME TO E STORE WHERE YOU CAN BUY DIFFERENT PRODUCTS ...
    {% endif %}
{% endblock %} 
{% block title %}
    {% if category %}
        {{ category.name }} - E STORE
    {% else %}
        See Our New Collections - E STORE
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'e_shopee:all_product_category' %}">OUR PRODUCT CATEGORY</a></p>
            </div>
        </div>
    </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}" >
</div>
    <br>
<div>
    <h1 class="text-center my_title"><b>{{category.name}}</b></h1>
    <p class="text-center">{{category.desc}}</p>
    <p class="text-center">{{category.price}}</p>
</div>
    {% else %}
<div class="my_image my_image_padding">
    <img src="{% static 'img/banner.png' %}" alt="OUR PRODUCTS" width="1300px">
</div>
    <br>
<div>
    <h1 class="text-center my_title">OUR PRODUCT COLLECTIONS</h1>
    <p class="text-center">Vegetables consist of a large group of plants consumed as food. Perishable when fresh but able to be preserved by a number of processing methods, they are excellent sources of certain minerals and vitamins and are often the main source of dietary fibre. The consumption of vegetables has increased significantly as consumers have become more health-conscious. Owing to the perishable nature of the fresh produce, international trade in vegetables is mostly confined to the processed forms.</p>
</div>
    {% endif %}

{% for product in products.object_list %}

<div class="card-deck">
  <div class="card text-center">
    <a href="{{Category.get_url}}"><img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}"></a>
    <div class="card-body">
      <h5 class="card-title">{{product.name}}</h5>
      <p class="card-text">{{product.desc}}</p>
        <p class="card-text">{{product.price}}</p>
    </div>
  </div>
  <div class="card text-center">
    <a href="{{Category.get_url}}"><img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}"></a>
    <div class="card-body">
      <h5 class="card-title">{{product.name}}</h5>
      <p class="card-text">{{product.desc}}</p>
        <p class="card-text">{{product.price}}</p>
    </div>
  </div>
  <div class="card text-center ">
   <a href="{{Category.get_url}}"><img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}"></a>
    <div class="card-body">
      <h5 class="card-title">{{product.name}}</h5>
      <p class="card-text">{{product.desc}}</p>
      <p class="card-text">{{product.price}}</p>
  </div>
</div>
</div>
{% endfor %}
<div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}

    <hr>
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-primary {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

e_shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> &copy; E store pvt ltd. All Rights Reserved</p>
</div>

e_shop/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'e_shopee:all_product_category' %}"><img src="{% static 'img/logo.png' %}" alt="logo image" width="80px" height="70px"></a>
  </center>
</header>

e_shop/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">E SHOP</a>
      </li>
      <li class="nav-item dropdown {% if 'e_shopee' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">E SHOP</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'e_shopee:all_product_category' %}">ALL PRODUCTS</a>
          {% for cart in links %}
          <a class="dropdown-item" href="{{cart.get_url}}">{{cart.name}}</a>
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_details' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:search_result' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search"  name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i> </button>
    </form>
  </div>
</nav>

e_shop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
    {% if category %}
        {{product.name}} - E STORE
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'e_shopee:all_product_category' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{product.img.url}}" alt="{{product.name}}">
            </div>
        </div>
        <div>
            <div class="col-3 col-sm-12 col-md-12 col-lg-12">
                <div>
                    <h1 class="my_prod_title"><b>{{product.name}}</b></h1>
                    <p>$ {{ product.price}}</p>
                    <p class="my_title"><b>ABOUT {{product.name}}</b></p>
                    <p>{{product.desc}}</p>
                    <p><b>CATEGORY :</b> {{product.category}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-center"><b>OUT OF STOCK</b></p>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

e_shop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    WE HAVE VARIETY OF PRODUCTS

{% endblock %}
{% block title %}

SEARCH
{% endblock %}
{% block content %}

<div>
    <p class="text-center my_search_text">YOU HAVE SEARCHED FOR : <b>"{{query}}"</b></p>
</div>
{% for product in products %}
<div class="container">
    <div class="row max_auto">
        <div class="my_bottom_margin col">
            <div class="card text-center" style="width: 13rem">
                <a href="{{Category.get_url}}"><img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.desc}}</p>
                        <h5 class="card-title">$ {{product.price}}</h5>
                    </div>
            </div>
        </div>
    </div>
</div>
{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text">O RESULTS FOUND</p>
</div>
{% endfor %}
{% endblock %}